### ISSUE TITLE
`check_minimize` should pass all the times instead of a majority number of times

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#127]
I understand the intention but it is a minimization problem and hence we would like `check_minimize` pass all the times instead of a majority number of times.

(Hopefully that day should come soon)

**Comment by glouppe** [comment]
Honest question: can we really guarantee convergence of a stochastic process, within a finite number of iterations?

**Comment by MechCoder** [comment]
No: But the first 3 benchmark problems should at least pass, don't you think? They are really easy.

On a related note, should we change the way we test `gp_minimize` currently (https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/tests/test_gp_opt.py#L18). It tests only for one random state.

**Comment by MechCoder** [comment]
I was concerned that if we make some breaking changes, the present tests may not be strong enough to catch those.

**Comment by betatim** [comment]
One idea would be to [mock](https://docs.python.org/3/library/unittest.mock.html) `np.random` so that it returns a sequence of numbers that we hand crafted and have verified lead to a certain state of the minimiser. This would be faster, give you more fine grained control/tests, and a lot of work.

Then running an overall minimisation like we do right now would become more of an integration test.
