### ISSUE TITLE
GP hyper-parameter optimisation

### ISSUE THREAD

**Issue by kegl** [scikit-optimize/scikit-optimize#137]
This is probably a complaint that belongs to the sklearn GP thread, but it's important for us. 

When using a GP for regression, we have three hyperparameters
1) RBF kernel length scale
2) the scaler before the RBF kernel
3) the noise

The scaler can be safely set to the unconditional std of the responses, but the other two should be optimized. Right now sklearn handles them completely asymmetrically. The length scale is auto-optimized (which IMHO completely breaks sklearn convention, but never mind), whereas the noise cannot even be entered as a hyper: one has to create a vector of size len(X) (as parameter alpha), init time!

I assume that at this point the noise is not optimized in the current skopt implementation (is it?). This is certainly not what we did in https://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization.pdf (ie we _did_ optimize the noise).

**Comment by glouppe** [comment]
Aren't you referring to the old implementation?

All of this can be set with the Kernel API of the new GP implementation (the one in 0.18-dev), and you can chose which ones are fixed or not. It is very powerful in what you can do.

E.g., in your case it should be something like 
```
from sklearn.gaussian_process.kernels import RBF, WhiteKernel
kernel = 1.0 * RBF() + WhiteKernel()
```

The `1.0 *` part effectively instantiates a `ConstantKernel` object whose hyper-parameter is optimised along the way. For RBF you can chose between isotropy and anisotropy, or decide parameters are fixed. The same for the WhiteKernel for which the noise level is estimated by default, but you can decide otherwise.

**Comment by glouppe** [comment]
As for the default kernel in `skopt`, we use the following https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/gp_opt.py#L139

**Comment by glouppe** [comment]
ping @jmetzen

**Comment by kegl** [comment]
How do you set a scalar alpha?

**Comment by glouppe** [comment]
`WhiteKernel(noise_level=42)`

**Comment by kegl** [comment]
Ok, great, I'm closing the issue :).

**Comment by glouppe** [comment]
Also in general, all hyper-parameters can be fixed to the provided initial values by setting the corresponding bounds to `"fixed"`. E.g., in this case it would be `noise_level_bounds="fixed"`. (I agree the documentation in scikit-learn could be improved to mention that.) But by default, all hyper-parameters of the kernel are optimized within their bounds.
