### ISSUE TITLE
Upper case strings for `forest_minimize` arguments

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#153]
Change `forest_minmize` arguments for `base_estimator` ([string arguments](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/tree_opt.py#L207-L212)) to upper case.

**Comment by jtsmith2** [comment]
I can make this change but I want to make sure I understand what you're wanting.  Are you wanting:

1. Make the arguments for `base_estimator` `"RF"` and `"ET"` instead of the current `"rf"` and `"et"`
or
2. Convert passed arguments for `base_estimator` to uppercase and compare to `RF` and `ET` so that the parameters is case insensitive.

Change 1 would likely require some documentation change as well (which is fine) so I just want to make sure I'm doing what the community wants to do.
