### ISSUE TITLE
Notebook showing how to persist/load a optimization result

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#190]
Persisting the result of an optimisation run is a useful tool to have. Either for plotting later on, creating a history of your research or sharing your results with others.

Having a notebook that gives a clear recommendation on how to do this would be nice. This avoids people doing "crazy" things.

Could be as simple as using `joblib.dumps(result)`

**Comment by betatim** [comment]
Opinions on providing `skopt.load` and `skopt.dump` as shortcuts to `sklearn.externals.joblib.dump/load`?

**Comment by glouppe** [comment]
No strong opinion, fine with me.

**Comment by betatim** [comment]
How should we handle `res.specs['args']['func']` when serialising the result object? It might contain weird things that can't be pickled and you might want to share your results with others who don't have the code for it. Sharing pickles between different users/python versions/machines is probably not the smartest thing anyway so should we worry about this? It could be that `joblib` makes promises on top of `pickle`??

I'd be interested in a method that allows the user to share their results with others (including their future self which might be on a different python version). This is potentially much harder to solve...

**Comment by MechCoder** [comment]
We can have an optional `return_specs`, which the user should be intelligent enough to set to be True if he wants to pickle or we can backport cloupickle, pyspark does it over here (https://github.com/apache/spark/blob/master/python/pyspark/cloudpickle.py)

**Comment by MechCoder** [comment]
Umm. Isn't using `joblib.load and dump` over-kill for our-case? It says it is useful only for large numpy arrays (http://scikit-learn.org/stable/modules/model_persistence.html) Our largest data structure is a list of lists.

**Comment by betatim** [comment]
Reason for suggesting `joblib` is that it is the recommended way to pickle scikit-learn classifiers, which can (in essence) be large numpy arrays. Not sure how applicable that is to our regressors.

I would strongly favour a solution where we don't have to maintain the pickling code ourselves (straight `pickle` or `joblib` or some other library).

I would make the "save specs or not" flag an argument of the `save()` function.

**Comment by MechCoder** [comment]
Hmm.. but then how do we serialize lambdas :(

**Comment by betatim** [comment]
Do we understand why they aren't picklable by default? The "hacks" I've seen to make them (and other common things that aren't picklable) are usually quite short, so it seems like there must be a good reason why the python devs don't just include that no? We should find out.

We should try and balance the (realistic) use cases with maintaining our own pickle substitute.

**Comment by mp4096** [comment]
I guess that saving results is really important to a lot of people and _most of them_ will have weird closures in `res.specs["args"]["func"]`. My current hack/workaround looks like this: 
```python
del res.specs["args"]["func"]

with open('result.pkl', 'wb') as f:
    pickle.dump(res, f)
``` 

What do you think of following:
* `skopt` should be able provide a closure-free variant of `OptimizeResult`. 
* both `pickle` and `joblib` approaches are demonstrated in examples (with pro & contra)
* the users should decide themselves which they want to use

**Comment by betatim** [comment]
Any opinions on [`dill`](https://github.com/uqfoundation/dill)? Would add an extra dependency.

I probably lean towards providing `skopt.save(res)` which removes `func` before saving via `pickle`.

**Comment by mp4096** [comment]
Haven't used `dill` before, but looks promising.

The problem is, my lambda is a thin wrapper around a MATLAB engine calling a Simulink model. So I guess there's nothing that can pickle it :smile:.

Just to make it unambiguous: What should `skopt.save(res)` do exactly? Should it...
* return a pickled bytestring?
* write to a file using `pickle`?
* return a clone of `res` without `func`?

I'd prefer the latter option. I think I can add this function and an appropriate example.

**Comment by betatim** [comment]
It should save things to a file. Looking back at the discussion and considering the naming convention in other packages it would probably make sense to introduce `skopt.dump(obj, fname)` and `skopt.load(fname)` (double checking the `pickle` interface). Probably could start life as something very similar to what you implemented for yourself using `pickle`.

**Comment by mp4096** [comment]
Thanks for the clarification! `load` and `dump` sound really reasonable. I'll take a look at the `joblib`'s interface as well.

Do you think `./skopt/utils.py` is an appropriate module for these functions?

**Comment by betatim** [comment]
> Do you think ./skopt/utils.py is an appropriate module for these functions?

👍

**Comment by betatim** [comment]
Are you still working on this? Otherwise I might jump on this.

**Comment by mp4096** [comment]
Sorry, I hope I'll have it done till Sunday evening. I'll also comment here in more detail in an hour or so.

**Comment by mp4096** [comment]
So, I'm very sorry for the double delay. I've done some research and tried to find different approaches to this problem.

* Idea 1: As discussed, implement `skopt.dump()` and `skopt.load()` using `pickle`. If the objective function is unserialisable, `skopt.dump()` throws a warning and proceeds by creating a deep copy of the optimisation results object, removing the objfun from the copied object and storing it into a file.
Unfortunately, one has to use a deep copy, which is not so good for very large objects (but hey, one should use `joblib` in this case anyway). This is PR #245 (WIP, waiting for your feedback before proceeding).
* Idea 2: Do not invent the wheel and just provide a notebook with some examples. Advantages: Fewer functions in `skopt` (= fewer tests required, fewer things that can go wrong) This is PR #246 
* Idea 3: Provide a `__getstate__(self)` method so that `pickle` or `joblib` know what to serialise. This proved to be a total tarpit. First, one cannot detect from inside of `__getstate__` if the objfun is serialisable or not. Second, it is impossible to monkey patch an instance of `OptimizationResult` with this method afterwards. One can do it, but then it causes an infinite recursion when actually calling `__getstate__`. So the only possibility is to subclass `OptimizationResult` in `skopt`, which is IMHO a bad idea.
* Idea 4: Use `pickle`'s [`persistance_id`](https://docs.python.org/3/library/pickle.html#persistence-of-external-objects). This seemed to be quite an elegant solution, pickle everything except for callables. However, I couldn't make the unpickler work. I suppose that removing all the callables during pickling somehow corrupts the resulting files.

Anyway, feel free to close one of either PRs; I'll try to finish the approved one without delays this time. :grinning:
