### ISSUE TITLE
Include expected compute time in the acquisition function

### ISSUE THREAD

**Issue by FedericoV** [scikit-optimize/scikit-optimize#211]
When optimizing a function over a large parameter space, certain parameter combinations might strongly increase computing time (for example, decreasing tol, or decreasing the amount of regularization).

This could be improved by estimating and accounting for changes in computing time as a function of parameters, and including this as a cost in the acquisition function.

**Comment by betatim** [comment]
Undecided if this needs code to support it or is "simply" something users need to take care of in their objective function.

**Comment by FedericoV** [comment]
If users take care of it in their objective function, then there is no way to separate objective function score and time it takes to compute a function.

**Comment by MechCoder** [comment]
Would that not lead to a situation for which the next candidate point is the one that optimizes the acquisition function that includes the time as a cost but the intention was just to minimize the original function without considering the time factor?

However, I'm interested in the approach in general. Would you be having a reference? :-)

**Comment by MechCoder** [comment]
Sorry, this seems to be a quite common approach that is followed. 

Page 6 of https://arxiv.org/pdf/1206.2944.pdf

and https://www.mathworks.com/help/stats/bayesian-optimization-algorithm.html?requestedDomain=www.mathworks.com#bva8tie-1

We can introduce another acquisition function that computes this expected objective / expected time.

**Comment by MechCoder** [comment]
I've started having a detailed look at this. Will issue a PR soon.

**Comment by betatim** [comment]
Being worked on in #369

**Comment by betatim** [comment]
Is there a good rule of thumb how to weight time and other score? I'm imagining a model where you reduce the number of layers/max_depth of trees which will lead to faster training times but potentially worse performance. Trying to understand how this is taken into account in EI per second.

**Comment by iaroslav-ai** [comment]
Here goes my a bit verbose opinion on this. 
 
Let p denote parameters vector being optimized with BO, f(p) objective being minimized, t(p) be the time necessary to evaluate an objective at point p.
 
The two cases need to be distinguished:
 
1. One is interested in finding global optimum of f, but wants to evaluate p with small t(p) first to arrive at “good enough” solutions fast. 
 
2. One is interested in solving a multiobjective optimization problem with vector valued objective given by v(p) := (f(p), t(p)) .
 
### Case 1. 
 
In this case the variance function should be modified to encourage evaluation of “fast” points first, but not the estimate of f, in order to ensure that when variance function becomes close to zero, the estimate becomes arbitrary close to f.
 
One way to achieve this would be to construct surrogates for f and t (f’, f’’ for mean and deviation, same for t’, t’’), and use acquisition function for example of the form (a variant of LCB)
 
A(p) = f’(p) - f’’(p) / (t’(p) + epsilon)
 
As eventually f’’(p) becomes something close to zero, the time term affect on the acquisition function diminishes. 
 
Conclusion: In case of 1, indeed a dedicated acquisition function is necessary. 
 
### Case 2.
 
In order to proceed with optimization in the first place, one needs to specify somehow an order on the points in space P where the optimization takes place, in order to be able to select between points, something like
 
p_0 <= p_1 <= p_2 … <= p_n

for all p_i in P, i = 1,2,3, ... . Note that given such order of points in the first place, one can construct a function f: P -> R for which this order will hold wrt input points: 
 
f*(p_0) <= f*(p_1) <= f*(p_2) … <= f*(p_n)
 
Such function is explicitly given for single objective function. However for multi - objective optimization, one still needs to define how the vector objective values are compared, that is, to establish an order of the form
 
v(p_0) <= v(p_1) <= v(p_2) … <= v(p_n)
 
Similar to above, given such order one can construct a function f: P -> R for which this order will hold: 
 
f*(v(p_0)) <= f*(v(p_1)) <= f*(v(p_2)) … <= f*(v(p_n))
 
Conclusion: Having a function that maps objective vector to a single value is fairly general and can be used to solve multi - objective optimization. I could see it as an extra parameter that is used to transform the objective value into single score that is used to compare different objective vectors. There could be a few predefined such vector to single value mapping (eg weighted sum, maximum of values, hypervolume etc). 
 
### Generalization of case 1 and 2.
 
In the case of PR as it is right now #369, the objective is a mix of both cases - a special acquisition function, which combines both mapping of v(p_i) to a single value and taking the variance into account. I think enabling user to provide a custom acquisition function generalizes both this and the cases above. It would be nice if users can easily define their own acquisition functions, for example based on existing ones and that can include mapping of objective vector into a single score.
 
I see an acquisition function as an estimator of its own, which takes a bunch of hyperparameters and surrogate for construction, is “fit” to the data by training (possibly multiple) surrogates on set of points and objectives, and makes “prediction” of how “interesting” some point is. 
 
For such generalization, I would suggest to have a number of BaseEstimator - like classes defined, which represent different acquisition functions, and use them instead of current approach. Something like a pipeline can be used to include objective vector transformation. In my view, this should lead to least boilerplate code and most generic approach. 
 
### Ok Iaroslav, this is great but what is your view on what in particular needs to be done in relevant PR?
 
1. We want to get soon to 0.4 milestone: implementation in PR as it is right now should be fine. There should be an issue on custom user acquisitions then though. 
 
2. It is ok if it takes a bit more time: use something inheriting from BaseEstimator for acquisitions which is quite general - could probably simplify the code also in few parts.

I am glad that you made it to the end of this comment. Feel free to let me know what you think of this :D

**Comment by MechCoder** [comment]
The acquisition function that you have mentioned in case 1 seems interesting.

For case 2: the user is still free to do a complex modeling inside the black-box function , the downside being that you cannot easily interpret the predictions obtained from the surrogate model.

Look at https://github.com/scikit-optimize/scikit-optimize/issues/148 to provide custom acquisition functions.
Not sure why you would want acquisition functions to be an `estimator`. For me it is a function that takes a fitted model and a number of other parameters as arguments and returns acquisition values at a number of data points. Anyway it seems unrelated to this issue :P

**Comment by iaroslav-ai** [comment]
Yeah, just some thoughts on how to have stuff generic. But we can think about this later (maybe also when someone shows need in something more generic). 
#148 - nice!
Yeah maybe this is a different issue :)
