### ISSUE TITLE
RFC: Switch to mkdocs?

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#270]
Shall we switch to a more mature and maintained documentation generator framework? E.g. http://www.mkdocs.org/ as used by Keras. 

The current builder is working OK, but incredibly hackish in retrospect.

**Comment by betatim** [comment]
Sure. How much hacking do we need to do to get the notebooks displayed nicely?

I am not a big fan of the menu on keras.io, seems to always hide what I am looking for. Probably just means we need to choose the theme wisely.

**Comment by betatim** [comment]
Do you want to take care of this and simultaneously do #261?

**Comment by glouppe** [comment]
Also, Sphinx now nicely supports gallery of notebooks.
https://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_seaborn_notebook.html#sphx-glr-tutorials-plot-seaborn-notebook-py

**Comment by MechCoder** [comment]
I used mkdocs to build this (http://scikit-garden.github.io/). Mkdocs is easier to write because it is markdown.
Sphinx can auto-generate API references from docstrings while for mkdocs I had to borrow some third-party code.

I did not invest much time yet in finding if it is possible to have the neat gallery of examples as linked above.

That being said, I like how the website looks right now.

**Comment by betatim** [comment]
Given that a lot of our actual documentation is in notebooks, should we give sphinx and the gallery a try?

**Comment by holgern** [comment]
Solved by switching to sphinx
