### ISSUE TITLE
Remove option `acq_optimizer="auto"`

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#274]
In order to simplify  slightly the API, I would vote for removing the `"auto"` value of `acq_optimizer`. 

I am not convinced we should default to random sampling as soon as one of the dimensions is not `Real`. 

I would rather default to `"lbfgs"` and have, maybe, a warning if one the dimensions isnt `Real`. (Which by the way does not mean that the optimization will fail.)

**Comment by MechCoder** [comment]
Sorry, but I would humbly disagree. It is all-right if it performs slow but no so-much if it provides a wrong output that cannot be relied on as the next candidate point. It is wrong because the output of the `fit_transform` for a `LabelBinarizer` is unreliable when the input is not in {0, 1}.

See: https://github.com/scikit-learn/scikit-learn/issues/7247

**Comment by glouppe** [comment]
My point is that there is nothing wrong with running `lbfgs` on integer or binary dimensions, as long as the solution returned is cast back correctly.

**Comment by MechCoder** [comment]
Ah yes, sorry you are right. I misread the documentation of the output of `inverse_transform` of `LabelBinarizer`

**Comment by glouppe** [comment]
Fixed.
