### ISSUE TITLE
Minimum value to report

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#335]
For the moment, the minimum value reported is the minimum value among the sampled points, for which we know the true value of the objective.

What do you think of also adding to the results the _expected_ location of the minimum, as modeled by the last model on the data points? (I.e., find the location of minimum over the (expected) decision surface and associate the expected function value to that minimum.)

If not packed into the results, a short helper `x, fx = expected_minimum(results)` would be handy.

**Comment by betatim** [comment]
I like the idea. Adding a helper might be better than putting it in the result object. Mostly because I can't think of a good way to name the attribute that won't lead to it being confused with the "other" minimum. Not sure which one we'd want people to use but having `res.minimum` and `res.actual_minimum` or what ever seems like a recipe for confusion.

---

😕 decision surface? You mean the surrogate model no?

**Comment by glouppe** [comment]
> You mean the surrogate model no?
Sorry, about that.

**Comment by MechCoder** [comment]
How do you infer that directly from the results object?

**Comment by glouppe** [comment]
> How do you infer that directly from the results object?

This is not immediate, but you can find the value x that minimizes that mean prediction of the GP.
(With a fine grid and/or by running lbfgs from the promising points.)

**Comment by glouppe** [comment]
In other words, this amounts to return the next best query point, turning off exploration completely.

**Comment by betatim** [comment]
I think I have a slight preference for [providing a helper](https://github.com/scikit-optimize/scikit-optimize/issues/335#issue-218215549) to do this.

**Comment by glouppe** [comment]
I'll work on this today!
