### ISSUE TITLE
Expose transform to the public API of dimensions and allow it to be a callable

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#379]
Currently we allow each dimension to be a `(lower_bound, upper_bound, prior)` tuple where prior can be "uniform" or "log-uniform". In order to allow more flexibilty, we can allow prior to be a callable that maps from the input space to some arbitrary space.

**Comment by MechCoder** [comment]
For instance, over here (https://github.com/scikit-optimize/scikit-optimize/blob/master/benchmarks/bench_ml.py#L65)

**Comment by betatim** [comment]
Isn't that more like a transformer?

**Comment by MechCoder** [comment]
In that case we should expose `transpose` in the public API (the 4th argument) and allow that to be a callable.

**Comment by MechCoder** [comment]
(Updated issue description_

**Comment by betatim** [comment]
What about encouraging users to use `Real(0, 23.23, transform=foo)` and such explicitly instead of passing just a tuple? In retrospect it feels like with the tuples it is already getting pretty messy to try and guess what the user meant (categories or lower and upper?).

At the moment my feeling is that we should encourage people to user tuples for "simple, quick, entry level" space specifications and then for anything more complicated or expert level use the explicit classes.

**Comment by MechCoder** [comment]
Yes, that is what I had meant, my bad if it implied that I had meant supporting tuples.

However, even doing that requires a user to construct a custom Transformer that supports a `rvs`, `transform` and `inverse_transform` which seems over-engineered . The method of doing the mapping in the objective function in the link mentioned above seems to be the most straightforward way.
