### ISSUE TITLE
Categorical dimensions in plotting functions

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#396]
Categorical dimensions are not very well supported in the plotting functions. See for example #395.

A good idea on how to show these dimensions is needed or providing a better error message that helps the user deduce what went wrong.

**Comment by marcelo-dalmeida** [comment]
Hi everyone

The errors that could be given are too broad

Per example, mine is: 
`ValueError: setting an array element with a sequence.`

It has been 2+ years since the official issue report and 1+ year since the fix first proposal.

If fixing it properly still isn't mature enough, please consider including some error handling, at least saying that is not supported, as it is somewhat difficult to associate that's the actual reason.


Thank you all for the work done and keep with the good work

**Comment by holgern** [comment]
Solved in version 0.7
