### ISSUE TITLE
Installation error:  ValueError: path xxx cannot be absolute

### ISSUE THREAD

**Issue by TsingQAQ** [scikit-optimize/scikit-optimize#558]
Hi there, 

thanks for this lovely optimize tool though I've encountered some problem when installing it.

I'm using the 
    `pip install scikit-optimize` 
command to install it while it raises the following error:
    `ValueError: path '/usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/arrayobject.h' cannot be absolute`
![default](https://user-images.githubusercontent.com/17846442/32977778-0e684326-cc6f-11e7-9ad4-6463b0eebdb1.png)
I have no idea what the problem was, my python version is 3.6.2.
Any hint for this? Many thanks

**Comment by betatim** [comment]
Did you install numpy before running `pip install scikit-optimize`? For the current release you unfortunately have to explicitly install numpy first. This will be fixed in v0.5

**Comment by TsingQAQ** [comment]
@betatim 
Currently I‘m using the Anaconda python , should I upgrade numpy or reinstall it?

**Comment by betatim** [comment]
Not quite sure what it means to use Anaconda python. If you start `python` and import `numpy` does that work in the conda environment you have?

What operating system do you use?

**Comment by TsingQAQ** [comment]
@betatim 
Yeah sure I've got numpy, scipy. The [Anaconda](https://www.anaconda.com/what-is-anaconda/) is a python distribution for data science, it has made many packages like scipy, numpy, sklearn in it.

My OS is Windows 10

**Comment by betatim** [comment]
Thanks for posting the screenshot. If you have numpy installed and can import it then I think this is a bug in https://github.com/scikit-garden/scikit-garden's `setup.py`. You should post an issue on that repository instead.

We recently removed the dependency on scikit-garden from scikit-optimize (because it is  tricky to get scikit-garden to work). So you can try installing scikit-optimize directly from GitHub with: `pip install https://github.com/scikit-optimize/scikit-optimize/archive/master.zip`

**Comment by TsingQAQ** [comment]
Really thanks for your suggestion.
I've got it installed through the this command. : )

**Comment by betatim** [comment]
Closing this then. Glad that worked and we are working towards releasing v0.5 where this will be fixed.
