### ISSUE TITLE
create scikit-optimize gitter channel?

### ISSUE THREAD

**Issue by mirca** [scikit-optimize/scikit-optimize#571]
Are the maintainers considering opening a channel on gitter? Personally, I found ``scikit-learn``'s gitter channel really useful.

I think ``scikit-optimize`` would benefit as much for having one. Especially to reduce the number of GitHub issues which would have been questions on gitter.

Cheers,
Zé

**Comment by betatim** [comment]
Let's try it out.

My thought on the "issues that are questions" topic was that we should be creating a FAQ or otherwise improving the docs. Maybe a bit more long term. My thinking was that gitter (or any chat really) doesn't let you easily search for old questions/answers.

Either way: https://gitter.im/scikit-optimize/Lobby is now a thing!
