### ISSUE TITLE
Unify GBRT and GP interfaces

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#60]
Based on: https://github.com/scikit-optimize/scikit-optimize/pull/34#discussion_r60404019

We should aim to converge on a unified interface where possible. It is too much work to duplicate all the acquisition functions etc.

**Comment by MechCoder** [comment]
Would you be able to handle this?

**Comment by betatim** [comment]
First we need some ideas on how to do it :)

**Comment by MechCoder** [comment]
My thoughts.

1. For now, we should have a common `gaussian_acquisition_function` since for both the conditionals are estimated to be gaussians. I would refactor the `_expected_improvement` in `gbrt_opt.py` into this.
2. For this functions, the `base_estimator` should have a `return_std` parameter.

wdyt?

**Comment by glouppe** [comment]
Is this still an issue?

**Comment by MechCoder** [comment]
only on github....
