### ISSUE TITLE
Catboost failure.

### ISSUE THREAD

**Issue by jdewsnip** [scikit-optimize/scikit-optimize#631]
I am getting a failure when using Integer search dimensions with Catboost. It looks like Catboost is using standard python 3.5 json serialisation internally when receiving parameters and this does not appear to be compatible with the integer values returned by skopt, this results in an error message like:

123 is not JSON serializable

Is there any simple way to return python ints from skopt rather than the numpy.int64? I realise that this could be reasonably argued to be outside skopt but the bug reports numpy json serialisation go back to 2015  and hence my interest in any workarounds.

**Comment by chschroeder** [comment]
I think it is reasonable for skopt to return the most primitive type in this case. As the the objective function is provided by you, you are free to convert any parameters before passing them to catboost.

If you have trouble with that then try to provide a minimal code example. I have been using xgboost / lightgbm a lot over the past few weeks, so i think we should get catboost running as well :)

**Comment by betatim** [comment]
I think this is something for catboost to fix or for people to implement in their objective functions. While in this specific instance it would be easy to implement in skopt I bet you in a few months we will find a package that wants a type which doesn't work with catboost :-/

**Comment by jdewsnip** [comment]
I am using the BayesSearchCV wrapper as shown below. So I am unsure if I can get at the parameters before they are passed to the estimator.

```python
from catboost import CatBoostRegressor
from sklearn.datasets import load_boston
from sklearn.model_selection import GridSearchCV
from skopt import BayesSearchCV
from skopt.space import Integer, Real

grid_space = {
    'iterations': [100, 300, 1000],
    'learning_rate': [0.003, 0.015,  0.1],
    'depth': [2, 6, 10]
}

bayes_space = {
    'iterations': Integer(100, 1000),
    'learning_rate': Real(0.003, 0.1, prior='log-uniform'),
    'depth': Integer(1, 10),
}

x, y = load_boston(return_X_y=True)


est = CatBoostRegressor(thread_count=8)

#opt1 = GridSearchCV(est, grid_space, cv=3, scoring="neg_mean_squared_error")
#opt1.fit(x, y)

opt2 = BayesSearchCV(est, bayes_space, cv=3, scoring="neg_mean_squared_error")
opt2.fit(x, y)
```

I have patched my code locally to get around the problem in optimizer.py

```python
    def _ask(self):
        """Suggest next point at which to evaluate the objective.

        Return a random point while not at least `n_initial_points`
        observations have been `tell`ed, after that `base_estimator` is used
        to determine the next point.
        """
        next_x = []

        if self._n_initial_points > 0 or self.base_estimator_ is None:
            # this will not make a copy of `self.rng` and hence keep advancing
            # our random state.
            next_x = self.space.rvs(random_state=self.rng)[0]

        else:
            if not self.models:
                raise RuntimeError("Random evaluations exhausted and no "
                                   "model has been fit.")

            next_x = self._next_x
            min_delta_x = min([self.space.distance(next_x, xi)
                               for xi in self.Xi])
            if abs(min_delta_x) <= 1e-8:
                warnings.warn("The objective has been evaluated "
                              "at this point before.")


        return [x.item() for x in next_x]
```

I am not clear if this would cover all cases as I don't have much experience with the internals of your code base, but I am happy to attempt to supply a fix. Alternatively, I can try the Catboost people.

**Comment by chschroeder** [comment]
Is it intentional that you are using the sklearn-style version of the interface (`BayesSearchCV`)? I don't think you can alter the parameters there.

In case you don't insist on using the sklearn interface, try using it the skopt API:
https://scikit-optimize.github.io/notebooks/hyperparameter-optimization.html

There you define the objective function explicitly. You could intercept at this point:
```
@use_named_args(space)
def objective(**params):
    reg.set_params(**params)
```
(Code taken from the example.)

**Comment by jdewsnip** [comment]
The reason I want to use BayesSearchCV is that it does a lot of other stuff e.g. cv, results, refit and best model. This gives me a nice way to compare the effectiveness of the hyperparameter tuning process just by swapping in and out BaseSearchCV based algorithms.

If I could make changes just in BayesSearchCV would you take a patch for it?

**Comment by betatim** [comment]
Why don't you create a PR with your patch from above and we see if any tests fail. I will try and experiment a bit myself tomorrow.

**Comment by jdewsnip** [comment]
ok I will take a look at this next week.

**Comment by betatim** [comment]
Let's keep it opened till there is a solution.

**Comment by Nyquis** [comment]
Has a solution been found for this issue?

**Comment by betatim** [comment]
I still think this is something that should be fixed in catboost or other packages. For scikit-optimize is it hard to know what various different packages need/expect/want in terms of types. In this case catboost should know that it can safely convert int64 to int before serialising it as JSON, but scikit-optmize can't be sure that this is the right thing to do for all packages. I assume some thinking like this is why the JSON serialiser doesn't just convert these two types automatically.

**Comment by david-waterworth** [comment]
I think you can assume that all other packages should work with standard python library types though - the issue is numpy is not part of the standard python library which is why json.dump() cannot serialise numpy.int64 (as it doesn't derive from int). If you only expose standard python library types through your interface, other packages are more likely to be work without modification.
