### ISSUE TITLE
"Dimension's name must be either string or None." when trying to create Dimension objects in python 2 after importing unicode_literals

### ISSUE THREAD

**Issue by lunik1** [scikit-optimize/scikit-optimize#667]
The following snippet produces the error:
```python2
from __future__ import unicode_literals
from skopt.space import Integer

Integer(1, 10, name="myInt")
```

This seems to be because the check for name is whether it is a `str` instance or None, but `from __future__ import unicode_literals` will change the instances to `unicode`. A few ways of performing this check robustly in python2 and 3 compatible ways are discussed [here on stackoverflow](https://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility).

**Comment by lunik1** [comment]
Looking at scikit's codebase, they seem to use `string_types` from `six`.

**Comment by betatim** [comment]
https://github.com/scikit-optimize/scikit-optimize/blob/c908bedd842ca538a71698a3b4bb40381a99903b/skopt/space/space.py#L160 is the line that causes the exception and that would need updating.

Maybe we should do our own thing to provide `string_types` instead of adding `six` as a dependency. Or we use `six` from scikit-learn.

ps. What do you mean with scikit's codebase? scikit-learn or one of the other scikits?

**Comment by holgern** [comment]
Python 2 is not longer supported
