### ISSUE TITLE
Callback with Optimizer()

### ISSUE THREAD

**Issue by RakiP** [scikit-optimize/scikit-optimize#750]
Hi, could one add a callback in the Optimizer() function for the Optimizer to be saved? (and loaded afterwards)?

Usecase
We have a set of 3 weights for a model which need to be optimized and all we do is measure the Click Through Rate, which has to be maximized. SInce we don't know the function of the CTR we use Optimizer instead of gp_minimize.
We have to wait one day for the CTR to be measured and therefore would like to save and load our optimizer.

**Comment by kennethloenbaek** [comment]
Hi,

If i understand you correctly, you want to be able to save the optimizer instance and then load it back?

If that is the case you should have a look at:
[skopt dump](https://scikit-optimize.github.io/#skopt.dump)
[skopt load](https://scikit-optimize.github.io/#skopt.load)
[stor-load example](https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/store-and-load-results.ipynb)

Even though it is made for result instances it also works with with Optimizer instance, since its basically "just" a serialization of the instance. 

Minimal example:
```python
opt_obj = skopt.Optimizer()
...

skopt.dump(opt_obj,"opt_obj.file")
```
Then you can close down Jupyter.

When opening Jupyter again it can be loaded as:
`
opt_obj = skopt.load("opt_obj.file")
`

I hope that was what you where asking for?!

**Comment by RakiP** [comment]
That is exactly what I was asking for. Thank you for your quick reply!

**Comment by iaroslav-ai** [comment]
Hey @kennethloenbaek , thank you for clearing up this issue! :)
