### ISSUE TITLE
Return type of `Space.rvs(x)` and `Space.inverse_transform(X)`

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#86]
Both `Space.rvs(X)` and `Space.inverse_transform(X)` return arrays of object dtypes. Are we okay with that?

**Comment by glouppe** [comment]
Indeed, this is not very nice, except when we have dimensions of mixed types. If all are integers or all are reals, then maybe should return an array of ints or an array of floats instead.

**Comment by betatim** [comment]
Started looking into this. It seems the dtype of the return value is determined by the type of the first `Dimension`:

```python
Space([('a', 'b', 'c'), (1, 3)]).rvs(n_samples=3, random_state=0)
# ->
[['b' '2']
 ['c' '2']
 ['b' '3']]
```

**Comment by betatim** [comment]
Actually has nothing to do with the type of the first dimension, but something else because

```
Space([(1, 3), ('a', 'b', 'c')]).rvs(n_samples=3, random_state=0)
# ->
[['1' 'b']
 ['2' 'b']
 ['1' 'b']]
```

**Comment by glouppe** [comment]
This only happens for mixed types. When all dimensions share the same type, it should be consistent. Isnt it?

**Comment by betatim** [comment]
Yes, when everything is of the same type it works as expected. Trying to work out how `np.transpose` chooses the type of the resulting array. I think this is where the "upset" is happening. My guess is it chooses the "most compatible" type somehow

**Comment by betatim** [comment]
For a mix of `int` and `float` you get `float` which also makes sense. The only annoying one (IMHO) is that for anything containing a string you end up with strings everywhere.

**Comment by glouppe** [comment]
Hmm, as part of #112, I minimize over int and real variables. With the current implementation however, `inverse_transform` returns an array of float in that case. This is problematic for hyper-parameter optimisation, since the semantic of the parameters may change depending on whether the values are integer or real (e.g. for `max_features` in trees). 

My opinion is that `inverse_transform` should really return a list of lists of values. This is I think the easiest way to guarantee that values are returned in their correct type.

**Comment by glouppe** [comment]
I'll start working on that, I think the solution should be close to my initial implementation, before we introduce the usage of `np.transpose` as a shortcut.

**Comment by glouppe** [comment]
Closing :beers:
